server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: my-app-json
    static_configs:
      - targets: ['localhost']
        labels:
          job: my-app
          __path__: /var/log/myapp/*.json
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: loggerName
            message: message
            userID: userID
      - labels:
          level:
          logger:
  - job_name: my-app-text
    static_configs:
      - targets: ['localhost']
        labels:
          job: my-app
          __path__: /var/log/myapp/*log